### ISSUE TITLE
[Request] Update to recent version of Marlin and update documentation

### ISSUE THREAD

**Issue by damvcoool** [bigtreetech/BIGTREETECH-SKR-mini-E3#114]
The current status of this repository uses a really old version of Marlin Bugfix-2.0.x, and the instructions to build the firmware have also changed quite a bit, specially with recent additions to Marlin bugfix-2.0.x

**Comment by pmjdebruijn** [comment]
While not official, you might be interested in:
https://github.com/pmjdebruijn/BIGTREETECH-SKR-mini-E3-V1.2

**Comment by damvcoool** [comment]
oh it's ok I got my own here:
https://github.com/damvcoool/Marlin-2.0.x-SKR-Mini-E3-v1.2

The request is not for me, it's for all the new people.

**Comment by damvcoool** [comment]
Thank you bigtreetech. Thanks for the update.
