### ISSUE TITLE
Question: does USB composite work for PC as of now?

### ISSUE THREAD

**Issue by brew99** [bigtreetech/BIGTREETECH-SKR-mini-E3#129]
I'm trying the latest vanilla marlin (nov 27th) with the USB env, and when I plug in my PC (Win10 nov update) to the mini E3, It asks to format the drive., but if I select to do that, it fails.   Device manager shows a USB COM port, and under drives it shows a ST drive, but it is not accessible.   I've tried 2 diff SD cards, and if I try to update drivers, it says I have the latest

Any help on this? (sorry don't know where else to ask

**Comment by brew99** [comment]
A user on the Marlin Discord channel found a work around by disabling the SD_CHECK_AND_RETRY in configuration.h, which allowed access to SD.   Could be further complications, so use at your own risk.

**Comment by reloxx13** [comment]
> 
> 
> A user on the Marlin Discord channel found a work around by disabling the SD_CHECK_AND_RETRY in configuration.h, which allowed access to SD. Could be further complications, so use at your own risk.

its not a workaround, its not even enabled by default in the marlin example config = fail configuration whereever u got it enabled from and it works fine without crc check since months for me.

**Comment by brew99** [comment]
Yes and that’s why I closed it on Dec 6.  I was working with that user
