### ISSUE TITLE
Run Away Bed Temperature!

### ISSUE THREAD

**Issue by Augcliffe** [bigtreetech/BIGTREETECH-SKR-mini-E3#161]
I just installed this card.  Immediately after turning on the power for the first time, the bed started increasing temperature and would not stop.  The bed quickly became too hot to touch (the stock card  never did that).  I tried going into the configurations and setting the max temperature to 60 and it ignored that and continued to climb.  I power cycled, I checked everything I could think to check.  I even flipped the "hot end thermistor" and "bed thermistor" cables on the circuit board because they aren't labeled and I wasn't sure which was which.  Regardless of that, the same symptom persisted.  Someone else on Amazon gave this board a 1 star review with the same problem I have.

**Comment by drphil3d** [comment]
You need to put the correct firmware on it. It comes with test firmware from the factory for automated testing.

**Comment by drphil3d** [comment]
Or you wired the bed into the power input instead of bed output

**Comment by Augcliffe** [comment]
> Or you wired the bed into the power input instead of bed output

This is what the problem was.  To be fair, all the diagrams and pictures I googled had it wrong too.  On the board I noticed the postive and negative different.

**Comment by SwiCago** [comment]
Can you not close your own issue request? Since you figured it out.
