### ISSUE TITLE
[BUG] (z axis noise )

### ISSUE THREAD

**Issue by spooky79** [bigtreetech/BIGTREETECH-SKR-mini-E3#162]
ender 3 skr e3 mini v1.2 marlin 2.0.1 problem - z axis big noise , on the marlin 2.0 bugfix  the problem does not occur

**Comment by spooky79** [comment]
[Configurationh .txt](https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/files/4014108/Configurationh.txt)
[platformio.txt](https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/files/4014109/platformio.txt)
[Configuration_advh.txt](https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/files/4014110/Configuration_advh.txt)

**Comment by spooky79** [comment]
hybrid threshold must be //

**Comment by Captian-Flotter-the-Otter-Spotter** [comment]
Thanks a lot! Had the same issue and with //hybrid threshold its gone.
