### ISSUE TITLE
Source for "firmware-bltouch-for-z-homing.bin"

### ISSUE THREAD

**Issue by USAFRichards** [bigtreetech/BIGTREETECH-SKR-mini-E3#174]
**Is your feature request related to a problem? Please describe.**

I am new. I would like to enable linear advance but I dont have source files for "firmware-bltouch-for-z-homing.bin". 

**Describe the solution you'd like**

Is there such a source file so I don't lose the current settings contained in it and I can enable linear advance?

**Describe alternatives you've considered**

I am new to compiling so I have tried but I dont know if all the features contained in "firmware-bltouch-for-z-homing.bin" are in the compliled file. For instance my Z is much noisier with the firware I compile. I would like to ad linear advance to "firmware-bltouch-for-z-homing.bin".

**Comment by HVJ17** [comment]
Are you compiling 2.0.1? It has a HYBRED on by default, This makes the Z scream. Who wants faster movement at the cost of noise??? I bought this board for the silence more than anything. I suggest going to adv.h and 
//#define HYBRID_THRESHOLD
Linear advance is about useless. I know there are some uses. Do you have a specific use for it?  I think it is enabled in the pre-compiled firmware. Have you printed the test file from Marlin? That will show if it is enabled or not.

**Comment by USAFRichards** [comment]
So I did figured out that Linear Advance was enabled in my build. I wanted to use it so I could get rid of or reduce the amount of bulging at the corners. Thank you for responding.
