### ISSUE TITLE
SKR Mini E3 V1.2 Firmware won't compile, even if I make no changes to it. 

### ISSUE THREAD

**Issue by Koyodee** [bigtreetech/BIGTREETECH-SKR-mini-E3#220]
Here is the [error message](https://pastebin.com/3fdb4cGG) I'm getting in Visual Studio (With Platformio extension)

**Comment by GhostlyCrowd** [comment]
"Please install Git client from https://git-scm.com/downloads"

**Comment by Koyodee** [comment]
I have installed the program, but it's [still not compiling](https://pastebin.com/Tt7B0crn). :(

**Comment by elhits** [comment]
you have to use STM32F103RC_btt_512K_USB

**Comment by Koyodee** [comment]
> you have to use STM32F103RC_btt_512K_USB

"Error: Unknown environment names". I've even tried the suggested names such as "STM32F103RC_bigtree_512K_NOUSB" and "STM32F103RC_bigtree_512K", but neither of them work either.

**Comment by Koyodee** [comment]
Here is the [error message](https://pastebin.com/PBYEqC4H)

**Comment by elhits** [comment]
I have downloaded the new firmware (2.0.5.3) and in platfotm.io the name is STM32F103RC**_btt_**512K_USB 
I have download to my C root directory because the default path was too large... may it helps you

**Comment by Koyodee** [comment]
> I have downloaded the new firmware (2.0.5.3) and in platfotm.io the name is STM32F103RC**_btt_**512K_USB
> I have download to my C root directory because the default path was too large... may it helps you

I did actually get it to compile using the latest version of marlin, but it made my printer a lot noiser (which I think is due to a bug in the latest version that makes the extruder consistently go above the stealthchop threshold). That's why I was hoping to get the BTT firmware working, as it's much quieter, and then I can change what I'd like to have enabled form there.

**Comment by HVJ17** [comment]
This is not a bug. If you are compiling your own firmware, disable hybridthreshold.

//#define HYBRID_THRESHOLD

**Comment by Koyodee** [comment]
You are a lifesaver! Thank you so much.
