### ISSUE TITLE
Marlin 2.0x Bugfix and Bigtreetech 

### ISSUE THREAD

**Issue by tucker15** [bigtreetech/BIGTREETECH-SKR-mini-E3#235]
### Steps to reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior**

**Actual behavior**

### Additional Information
* Include a ZIP file containing your `Configuration.h` or use [Pastebin](https://pastebin.com/) and paste a link in this issue.
* Provide pictures or links to videos that clearly demonstrate the issue.

**Comment by GhostlyCrowd** [comment]
ok?

**Comment by tucker15** [comment]
Accendentally hit enter, thats all.
