### ISSUE TITLE
[BUG] USB device not recognized when plugging in thermistors

### ISSUE THREAD

**Issue by hr121** [bigtreetech/BIGTREETECH-SKR-mini-E3#290]
### Bug Description

When plugging in the either of the temperature sensors to the board the device can no longer be recognised. However if i disconnect the temperature sensors it seems to connect again. So i think the issue is with the temperature sensor settings or something along that line. This is on a custom built printer.

Mother board is the skr mini e3 v1.2

### My Configuration

Link to config files: [https://drive.google.com/file/d/17LR1ErjJTCcIPhGYAJFluQ76doJpb8QW/view?usp=sharing]

[config.zip](https://github.com/MarlinFirmware/Marlin/files/4776955/config.zip)

### Steps to Reproduce

With the config files linked above, having the temperature sensors disconnected the device is recognised fine and stepper motors can be controlled and homed. Then powering down the device, reconnecting the temperature probe and powering the device back on the device can no longer be connected to.

#### Additional Information

two white wires in the bottom left hand corner is the wires for the hotend thermal probe and the purple and blue wires next to that one is the wires for the heated bed.

![20200614_184857](https://user-images.githubusercontent.com/32442353/84600290-2ba49d00-ae70-11ea-8530-22726a315716.jpg)
![20200614_184855](https://user-images.githubusercontent.com/32442353/84600291-2c3d3380-ae70-11ea-8761-c9156ca06bbf.jpg)
![20200614_184925](https://user-images.githubusercontent.com/32442353/84600292-2cd5ca00-ae70-11ea-9487-7b14a1f6e30c.jpg)

**Comment by mitrofan110** [comment]
One of the sensors probably has contact with the metal case of the printer ..

**Comment by hr121** [comment]
The sensor was faulty
