### ISSUE TITLE
Power supply settings

### ISSUE THREAD

**Issue by Spitfiredriver** [bigtreetech/BIGTREETECH-SKR-mini-E3#34]
Got my new BTT SKR mini E3 V1.2 today. Connected it as per the old Creality board and it is dead (no power led).
Have I missed something regarding jumper settings?There is 24V on the input pins and 24v between the fuse and ground so that is ok. The cooling fan starts as soon as power is supplied. I checked for 5V at C37 and there is no voltage across it.

**Comment by csgoat2004** [comment]
Did you solve this issue? I am having the same problem.
