### ISSUE TITLE
Latest firmware 2.0.6 stepper motors much louder?

### ISSUE THREAD

**Issue by urshurak776** [bigtreetech/BIGTREETECH-SKR-mini-E3#389]
Just downloaded the latest firmware 2.0.6 for my SKR Mini E3 V2.0 board (posted a couple days ago) and the unit is much louder than the 2.0.x bugfix drivers and feature set seems a lot smaller in the menus.  Thinking of going back.  I have an Ender 3, no BLTouch or anything.

UPDATE:  Went back to 2.0 Bugfix and nice and quiet again.  Again went back to 2.0.6 and LOUD.  Did they not load the drivers?  Went back to 2.0.x Bugfix again and staying there for now.  I thought I was crazy and even my wife (who knows nothing about this stuff) said definitely louder.  It was like the original Creality board.  I think they forgot the 2209 stepper drivers or something.

**Comment by davidv3rs** [comment]
Came here to say this. Also baby stepping doesn't seem to work. Get an "Unknown command: M290..." error on the display. Was going to open a new issue but I'll just go back to 2.0 bugfix.

**Comment by chiibis** [comment]
Same issue here. Have to install previous version because of noise.

**Comment by Halvehak** [comment]
Same issue here. Installed latest 2.0.6 firmware and now the stepper motors making a grinding noise.

**Comment by davidv3rs** [comment]
@chiibis where do you get the previous version source?

**Comment by davidv3rs** [comment]
Found the fix:

Configuration_adv.h
Uncomment lines 2407-2409

```
  /**
   * TMC2130, TMC2160, TMC2208, TMC2209, TMC5130 and TMC5160 only
   * Use Trinamic's ultra quiet stepping mode.
   * When disabled, Marlin will use spreadCycle stepping mode.
   */
  #define STEALTHCHOP_XY
  #define STEALTHCHOP_Z
  #define STEALTHCHOP_E
```

Looks like Stealth Chop was turned off.

**Comment by urshurak776** [comment]
Thanks David!   Wonder why they changed it?

**Comment by urshurak776** [comment]
What does M502 and M500 do?

**Comment by davidv3rs** [comment]
> What does M502 and M500 do?

Resets your EEPROM.

**Comment by urshurak776** [comment]
Thanks David!

**Comment by urshurak776** [comment]
So, I downloaded the latest Marlin 2.0.6.1.  Followed the guide on reddit For the SKR Mini E3 2.0 and watched video from Chris Riley (Chris’ basement in youtube.). Compiled it, exported the bin file and flashed it to the board. Everything worked great EXCEPT my computer would recognize the board when plugged into my PC.  Drivers were fine.  Just to check, I flashed back to 2.0.X bug fix and my computer recognized it again.  Checked the serial port is -1 and serial port 2 is 2.  Not sure.  Good news is the stepper drivers were nice and quiet again, but I need functionality with the computer.  

I also tried overwriting the config.h and advanced.h files  with the ones from BTT’s site but it wouldn’t compile.  Not sure why.  So, for now, sticking with the 2.0.x bugfix.

**Comment by davidv3rs** [comment]
> So, I downloaded the latest Marlin 2.0.6.1. Followed the guide on reddit For the SKR Mini E3 2.0 and watched video from Chris Riley (Chris’ basement in youtube.). Compiled it, exported the bin file and flashed it to the board. Everything worked great EXCEPT my computer would not recognize the board when plugged into my PC. Drivers were fine. Just to check, I flashed back to 2.0.X bug fix and my computer recognized it again. Checked the serial port is -1 and serial port 2 is 2. Not sure. Good news is the stepper drivers were nice and quiet again, but I need functionality with the computer.
> 
> I also tried overwriting the config.h and advanced.h files with the ones from BTT’s site but it wouldn’t compile. Not sure why. So, for now, sticking with the 2.0.x bugfix.

Hmm, I'll look into it.

**Comment by urshurak776** [comment]
Think I figured it out.  In the platformio.ini file I didn’t Change default_envs = STM32F103RC_BTT_512K. 

I should have copied all three files over and made your changes on the advanced configuration file.  I’ll try it in morning and report back. 

Thanks David.

**Comment by chiibis** [comment]
> @chiibis where do you get the previous version source?

Not sources, just previous `firmware.bin` file. 

From history on github:

![Opera Snapshot_2020-09-13_191050_github com](https://user-images.githubusercontent.com/7037967/93023069-10733600-f5f5-11ea-9493-338a2c8e1435.png)

**Comment by davidv3rs** [comment]
> > @chiibis where do you get the previous version source?
> 
> @davidv3rs Not sources, just previous `firmware.bin` file.
> 
> From history on github:
> 
> ![Opera Snapshot_2020-09-13_191050_github com](https://user-images.githubusercontent.com/7037967/93023069-10733600-f5f5-11ea-9493-338a2c8e1435.png)

Ahh, good to know. Thank you!

**Comment by zurtox** [comment]
Yes, I'm facing the same issue with the Mini v1.2

**Comment by Disk1of5** [comment]
Same issue.

**Comment by timqui** [comment]
I see an update 18 hours ago for Ender 3 firmware, but I didn´t try it.

 [https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/tree/master/firmware/V2.0](https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/tree/master/firmware/V2.0)

**Comment by Disk1of5** [comment]
I can't test until the binaries for the firmware-bltouch-for-z-homing.bin drop.

**Comment by urshurak776** [comment]
Looks like the Stealth Chop is enables for each axis.  Won’t be ale to try it until tomorrow.

**Comment by urshurak776** [comment]
Downloaded firmware and flashed to board.  Works great.  Nice and quiet!
