### ISSUE TITLE
[FR] Bootloader for all devices

### ISSUE THREAD

**Issue by jernejp21** [bigtreetech/BIGTREETECH-SKR-mini-E3#425]
Is it possible to get bootloader for all the boards? I'm doing some testing and have very good debugger, which doesn't need a boot loader for uploading FW. But currently I'm facing an issue with USB not working. Windows don't see any device connected.

I would need bootloader to see if this is SW problem or HW defect.

**Comment by 407s** [comment]
Bootloader not Open Source. They will reject your request.
