### ISSUE TITLE
[BUG] (SKR mini E3 v1.2 no flash with SD )

### ISSUE THREAD

**Issue by Alexkey2200** [bigtreetech/BIGTREETECH-SKR-mini-E3#428]
Hi, I´ve  a SKR mini E3 v1.2 whit BlTouch. But ....

I have uploaded the marlin firmware several times modifying the autobed leveling, bootscreen and grid parameters to my liking. But this last time I needed to reverse the rotation of the extruder motor but when uploading it to SD the SKR does not take the new firmware. And tried everything in the forums, from formatting the SD, updating VStudio and the Platformio Core, restoring the default settings in the EEPROM, disconnecting the BLtouch. But nothing works for me, it should be noted that the sd reader of the plate works since I always print from there.

Does someone know how to solve this problem?

**Comment by Switchcrafter** [comment]
can you expand on "SKR does not take the new firmware"?  

After booting off the SD card containing the new firmware.BIN,  does the file extension change to firmware.CUR after it boots?

**Comment by Alexkey2200** [comment]
Hi, Switchcrafter.

       Yes te firmware change to te firmware.CUR after it boots. I managed to find the problem and it turns out that I had corrupted marlin sources for some reason (I have them in OneDrive and I think the modifications on the disk were not updated), I downloaded the marlin 2.07 file and it went up perfectly without problems.
