### ISSUE TITLE
region `rom' overflowed

### ISSUE THREAD

**Issue by seboo30** [bigtreetech/BIGTREETECH-SKR-mini-E3#46]
When trying to build : 

.pio\build\STM32F103RC_bigtree\firmware.elf section `.rodata' will not fit in region `rom'
region `rom' overflowed by 1740 bytes

Someone got an idea?

**Comment by seboo30** [comment]
'%02u' directive writing between 2 and 10 bytes into a region of size between 0 and 4

Resolved ....

**Comment by JJJMlo** [comment]
Hi,

Where exactly we should change it. because I'm pretty new and i have no idea.
