### ISSUE TITLE
Firmware 2.0.7.2 preconfigured never stop the fan during printing. To print ABS i need to stop fan.

### ISSUE THREAD

**Issue by cybsit** [bigtreetech/BIGTREETECH-SKR-mini-E3#482]
Hi, I'm using BIGTREETECH SKR mini E3 V2 on an Ender 3 Pro printer with BlTouch.  I loaded the latest preconfigured firmware with BlTouch and found that I can't print ABS because the fan never stops during printing even if the fan speed is set to 0% or no cooling.

**Comment by Seelenkind** [comment]
The chip for the fan breaks very quickly. To test, you can downgrade to Marlin Bugfix 2.0 without BL Touch. If it still runs continuously, the board is defective and has nothing to do with the firmware.

**Comment by cybsit** [comment]
Hi, the fan runs all the time when it prints even if I set it without a fan.  when it finishes printing, the fan stops.Pe 5 ian. 2021 01:31, Hilmi Sönmez <notifications@github.com> a scris:
The chip for the fan breaks very quickly. To test, you can downgrade to Marlin Bugfix 2.0 without BL Touch. If it still runs continuously, the board is defective and has nothing to do with the firmware.

**Comment by davidrichter-cz** [comment]
Hi, I have the same problem with the blower fan, I do not have a BL touch, the problem occurred by changing the default display to TFT24. So I don't believe there is a bug on the E3 MINI board but in the firmware. Any advice?

**Comment by cybsit** [comment]
when I want to print ABS or PETG I use firmware 2.0.6.1 which does not start the fan at all.  for other prints where it doesn't matter that the fan is running all the time I use firmware 2.0.7.2

**Comment by cybsit** [comment]
hopefully these issues will not appear in the next firmware update

**Comment by alvarini** [comment]
I have compiled my own Marlin with last version available and when plugging layer Fan to Fan 0 is always 100% and not responding to pwm signals

**Comment by davidrichter-cz** [comment]
Problem solved, just flip the fan connectors, then everything works as it should.

**Comment by davidrichter-cz** [comment]
Problem solved, just swap the connectors FAN0 and FAN1 fans, then everything works as it should.

**Comment by cybsit** [comment]
it worked for me, thanks.  case closed!!!

**Comment by alvarini** [comment]
not solved for me, I flipped the connectors and I got fire in the black component over the Fan0 connector

**Comment by davidrichter-cz** [comment]
Swapping connectors FAN0 and FAN1 cannot cause a fire. You have another fatal mistake somewhere. Pay attention to 12V and 24V power supply and fan voltage. Pay attention to the polarity of the FAN!

> nevyřešený pro mě, otočil jsem konektory a dostal jsem oheň v černé komponentě přes konektor Fan0
