### ISSUE TITLE
skr mini e3 v1.2 with STM32f103RET

### ISSUE THREAD

**Issue by PavelKir-01** [bigtreetech/BIGTREETECH-SKR-mini-E3#486]
the board came with a burnt-out microcontroller STM32F103RCT
Soldered STM32F103RET
Standard firmware is not suitable
Tell me how to configure platformio.ini

**Comment by PavelKir-01** [comment]
Please help me

**Comment by radek8** [comment]
look here
https://github.com/MarlinFirmware/Marlin/issues/15254
