### ISSUE TITLE
[FR] PTD - Power detection

### ISSUE THREAD

**Issue by cookins** [bigtreetech/BIGTREETECH-SKR-mini-E3#490]
hello
i see no explanation anywhere about some port on skr mini e3 v2 board diagram
![image](https://user-images.githubusercontent.com/7893051/104866328-f94ba880-5946-11eb-8f84-43c5edb1a47a.png)
can i get some details and i think it needed to publish info about this port.
as i see its pin12? what max voltage allowed? whats NC?
thanks

**Comment by cookins** [comment]
i found that there place for module call BTT UPS 24v.
so it is something for, at least.
now im curious, if its allowed to use PC12 (pin12?) port and what max voltage is allowed?

**Comment by dircr** [comment]
NC = Not Connected?

**Comment by cookins** [comment]
already figured - its for this module:
http://ae01.alicdn.com/kf/H33cff675e51c407888889ff323de6c9aO.jpg_q50.jpg
