### ISSUE TITLE
function call is not allowed in constant expression

### ISSUE THREAD

**Issue by bASHer91** [bigtreetech/BIGTREETECH-SKR-mini-E3#51]
How to i solve this? Followed all instructions step by step.

Thanks

![s2uvQlp](https://user-images.githubusercontent.com/56788808/67158358-06867b80-f32f-11e9-8734-be91464aefda.png)

**Comment by HGDrenth** [comment]
I think PlatformIO had an update, try reinstalling. 
I also had to update to python 3.8 -> dont forget to tick the PATH option during installation.

**Comment by bASHer91** [comment]
Ive only just installed it all, still the same :(

how do i find out what python im running?

**Comment by nickjgriff** [comment]
I have this problem with a earlier version of marlin it's only about 2 weeks old and working fine but as soon as I upload it I get the same 41 errors and the firmware is unchanged from the last time I built it ?

**Comment by nicwilson58** [comment]
thank you, installing Python 3.9 in windows,  then installing,  Python for VSCode and Python Extensions for VSCode fixed this issue for me too.

**Comment by 150612360** [comment]
[python-3.8.0-embed-amd64.zip](https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/files/10713491/python-3.8.0-embed-amd64.zip)
did not work please HELP

**Comment by HTMLdu** [comment]
> [python-3.8.0-embed-amd64.zip](https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/files/10713491/python-3.8.0-embed-amd64.zip) did not work please HELP

Download latest version which is 3.9
