### ISSUE TITLE
Change filament option gone from printer menu.

### ISSUE THREAD

**Issue by PLAyerNos** [bigtreetech/BIGTREETECH-SKR-mini-E3#53]
Hi All,
There is no change filament option and Cura change filament G code is ignored by my printer.
That's not good.

**Comment by Gummibaer** [comment]
Enable
//#define ADVANCED_PAUSE_FEATURE
in Configuration_adv.h

**Comment by PLAyerNos** [comment]
Will try after print.
Many thanks!

**Comment by PLAyerNos** [comment]
Managed to do it after many attempts...
Had to disable few things to free memory.
I hoped this board will be capable to do more things.
Many thanks again!

**Comment by nimrod86** [comment]
I'm new to this, where were you able to make the change in Configuration_adv.h? Do I have to recompile Marlin myself to change this?
