### ISSUE TITLE
Heated bed doesn't work on CR-10 (stock).

### ISSUE THREAD

**Issue by oreo-ux** [bigtreetech/BIGTREETECH-SKR-mini-E3#54]
Since installing the SKR mini E3 in my CR-10 the heated bed won't heat up. The Temps. are also jumping around 20-21 degress Celsius.
Only the bed is affected (hotend works flawlessly).
I've already checked the connections and didn't find any flaws.
Maybe it's an error in the Marlin code.
Thank you in advance for your help!

**Comment by kubik256** [comment]
I've setup and calibrate BED PID with `M303E-1C10S70` and this config:
```
#define PIDTEMPBED

//#define BED_LIMIT_SWITCHING

/**
 * Max Bed Power
 * Applies to all forms of bed control (PID, bang-bang, and bang-bang with hysteresis).
 * When set to any value below 255, enables a form of PWM to the bed that acts like a divider
 * so don't use it unless you are OK with PWM on your bed. (See the comment on enabling PIDTEMPBED)
 */
#define MAX_BED_POWER 255 // limits duty cycle to bed; 255=full current

#if ENABLED(PIDTEMPBED)
  //#define MIN_BED_POWER 0
  //#define PID_BED_DEBUG // Sends debug data to the serial port.

  // CREALITY ENDER 3
  #define DEFAULT_bedKp 73.95
  #define DEFAULT_bedKi 13.57
  #define DEFAULT_bedKd 268.70
```

It works fine on Ender 3, but I don't  know if CR-10 has larger / more power hungry bed. If so, external mosfet could be useful, maybe mosfet on mini E3 can't handle that amount of current.

Also I have aluminium heatsinks on all mosfets ;)

**Comment by oreo-ux** [comment]
I changed the code but the problem wasn't solved. The bed was working flawlessly until I've changed the mainboard.

**Comment by oreo-ux** [comment]
I've checked the corresponding connections. With my old board the bed does heat up normally = no error in the wireing. All the corresponding parts are ok. Could it be that the board has some faulty soldering?

**Comment by kubik256** [comment]
Give it a try and measure voltage on heated bed output with heated bed turned on / bed temperature set ;)
![image](https://user-images.githubusercontent.com/6485448/67280691-040e5800-f4ce-11e9-97aa-901f0d5222bb.png)

**Comment by oreo-ux** [comment]
I fixed it! The problem was that the board has the wires for the heated bed (Cr-10 stock one) swapped.
Just swap the two wires and it should work.
Thank you kubik256 for your help!
