### ISSUE TITLE
tft35 and skr mini e3 v2.0 Simulation mode don't work 

### ISSUE THREAD

**Issue by ChevalierLouis** [bigtreetech/BIGTREETECH-SKR-mini-E3#546]
Hello

I would like to know which screen did I use on the marlin firmeware for the skr mini e3 v2.0 with the tft35 

I can use the screen in grafical mode but not with the simulation  

I have try with only the 5pin plug ==> only the grafical interface work 
I have try with only the 10pin plug ==> only the grafical interface work 
I have try with both plug ==> only the grafical interface work 
but never the simulation mode work 

have a nice day !!!

**Comment by radek8** [comment]
What version of TFT 35 do you have?
How Are You Involved? Send a photo of the connection.
What have you configured in Marlin and TFT? Submit configuration files for review.

**Comment by ChevalierLouis** [comment]
_What version of TFT 35 do you have?_
==>I don't know, but I bought it this month there is the new ui on it I will check it this evening

_How Are You Involved? Send a photo of the connection._

![189004879_510241066682161_273371790493338636_n](https://user-images.githubusercontent.com/44653107/119450726-a179df80-bd34-11eb-8bac-6aa509aac0b1.jpg)
 
_What have you configured in Marlin and TFT? Submit configuration files for review._

==> I put //louis for each modification
[configuratio.h.txt](https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/files/6537062/configuratio.h.txt)

**Comment by radek8** [comment]
You can at least take a picture of the display from the connector side

**Comment by ChevalierLouis** [comment]
Of course 
![Uploading IMG_20210525_183923.jpg…]()

**Comment by ChevalierLouis** [comment]
Of course
![IMG_20210525_183923](https://user-images.githubusercontent.com/44653107/119541611-e92d5500-bd8e-11eb-9a38-6e836bee5462.jpg)

**Comment by radek8** [comment]
According to the photo you have the TFT35MZ
And the problem with not displaying Marlin mode is in a poorly connected 10Pin cable.

![image](https://user-images.githubusercontent.com/46979052/119551696-34993080-bd9a-11eb-99a3-5c0b33cedf66.png)

**Comment by radek8** [comment]
![image](https://user-images.githubusercontent.com/46979052/119551823-57c3e000-bd9a-11eb-9eba-5f9eb3824ff9.png)

**Comment by ChevalierLouis** [comment]
Thanks a lot , I am so stupid;) It work

**Comment by radek8** [comment]
Unfortunately, without an encoder only through the display, Marlin will be difficult to control. The right part of the display simulates an encoder, but it is not ideal.

**Comment by radek8** [comment]
Can you close the ticket if your problem is solved?
Thank you
