### ISSUE TITLE
Could the extruder and mobo fans be slowed down? (Fan1 and the other)

### ISSUE THREAD

**Issue by Chak10** [bigtreetech/BIGTREETECH-SKR-mini-E3#55]
The noise is much higher than the stock, perhaps reducing speed would be better.
![Screenshot (9)](https://user-images.githubusercontent.com/24445137/67245531-82caad00-f45c-11e9-9d51-737bf8890c24.png)

**Comment by bojanpotocnik** [comment]
Unfortunately not as both are connected to the 24 V power supply directly.
![BTT SKR mini E3 V1 2sch pdf](https://user-images.githubusercontent.com/4901762/67642572-5061f980-f90d-11e9-8171-1adfcd6a74c1.png)

**Comment by Chak10** [comment]
@bojanpotocnik Thanks for the reply. I was thinking of using two potentiometers.

**Comment by ManiRX100** [comment]
Hi 
Sorry for commenting on the closed issue. The fans are two noisy. Is it possible to use the below PWM marlin codes to slow down the fan?
//#define FAN_MIN_PWM 50
//#define FAN_MAX_PWM 128
These are commented out in configuration_adv.h. Or its not at all possible as the fans are connected to 24V supply directly ?
