### ISSUE TITLE
Bltouch installed correctly and screen is black.

### ISSUE THREAD

**Issue by gtdaniel101** [bigtreetech/BIGTREETECH-SKR-mini-E3#554]
I have installed a bltouch to my ender 3 pro that has a skr mini 1.2 motherboard. I flashed the firmware and plugged in the bltouch with the orders being blue/brown, red, yellow. Then black, white. Whenever I turn the power on, the fans will turn on but the screen wont. If I unplug either the blue or red wire the screen will turn on but I lose the ability to control the bltouch at all.

**Comment by radek8** [comment]
Looks like you have the BL-touch wires connected in the wrong order.

**Comment by radek8** [comment]
send photo of engagement

**Comment by gtdaniel101** [comment]
![IMG_1110](https://user-images.githubusercontent.com/86484915/123479423-e791bf80-d5ce-11eb-8e9b-c4e509babf41.jpg)

**Comment by gtdaniel101** [comment]
then the black and white ones are plugged into the ztop

**Comment by CamWynd** [comment]
I had this problem too. I had two wires backwards in the plastic connector; what colour wires does your unit have?

**Comment by gtdaniel101** [comment]
blue red yellow black and white

**Comment by radek8** [comment]
bad photo
send new photos to see where all the BL-Touch wires are connected
Also take a picture of the BL Touch to issue a color sequence.

I don't see a connected display anywhere. it cannot work if it is not connected.

**Comment by radek8** [comment]
To which connector is black and white connected?
PROBE or Z-STP?

**Comment by radek8** [comment]
Submit configuration files

**Comment by gtdaniel101** [comment]
![IMG_1111](https://user-images.githubusercontent.com/86484915/123485087-7276b800-d5d7-11eb-8a5d-427ddaf98a83.jpg)
I unplugged the display just so I could take the picture, the wires were covering it up. The black and white are connected to the Z-STOP

**Comment by gtdaniel101** [comment]
![IMG_1112](https://user-images.githubusercontent.com/86484915/123485258-bcf83480-d5d7-11eb-8533-f7d5000a7150.jpg)
Hopefully, this is a better picture, I don't have a 3pin plastic piece so I just used a two-pin and put the third in, no wires touch so it should be fine.

**Comment by radek8** [comment]
Then you have it completely badly connected

**Comment by gtdaniel101** [comment]
Sure it isn't pretty but electrically everything works, nothing is touching, everything is separated by plastic and each pin has a solid connection to the board.

**Comment by radek8** [comment]
The colors of the cables on the BL -touch are folded back

**Comment by gtdaniel101** [comment]
What do you mean by that? I don't understand

**Comment by radek8** [comment]
![image](https://user-images.githubusercontent.com/46979052/123486011-8f2ce300-d60b-11eb-8d19-dfa1143bd66e.png)

**Comment by radek8** [comment]
![image](https://user-images.githubusercontent.com/46979052/123486201-e0d56d80-d60b-11eb-9706-3524d9879fd6.png)

**Comment by gtdaniel101** [comment]
![image](https://user-images.githubusercontent.com/86484915/123486513-2bd68d00-d5da-11eb-8ac6-c464dfffe0a5.png)
Thank you so much, I changed them around and it is working now. I was going off of this picture and multiple others that showed the same thing for what the wires were

**Comment by radek8** [comment]
You came up with the right picture, but your connector has poorly folded colors (in the opposite direction)
