### ISSUE TITLE
ANET E16 with BTT skr mini e3 v2.0 + tft35 e3 v3.0

### ISSUE THREAD

**Issue by Warlord3469** [bigtreetech/BIGTREETECH-SKR-mini-E3#558]
i just recently purchased btt skr mini e3 v2.0 + tft e3 v3.0 on amazon to get away from the anet 8bit board might be a mistake since i really dont know what im doing unless youtube shows me can anyone point me in the right direction on someone who has done this modification or help me compile the firmware so i can upload it to my board thanks.

**Comment by TheRealRazr** [comment]
I've found that as a beginner this video was the easiest to follow for setting up the firmware and flashing it to the board:
https://youtu.be/GQlAN88ebNM

If you're setting up a bltouch here is a good video for learning to configure it in the firmware:
https://youtu.be/7le9L2LMY-U
