### ISSUE TITLE
SKR mini E3 V3.0 Marlin problem with CR Touch z homing

### ISSUE THREAD

**Issue by Wonkothsane** [bigtreetech/BIGTREETECH-SKR-mini-E3#593]
Board: SKR mini E3 V3.0
Printer: Ender 3 Pro
Z probe: CR-Touch

### Description
CR-Touch will not Z-home using BTT provided Marlin Firmware.
I have installed this Firmware: [firmware-ender3-bltouch-for-z-homing.bin](https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/blob/master/firmware/V3.0/Marlin/firmware-ender3-bltouch-for-z-homing.bin)

### Steps to reproduce
1. Install SKR Mini E3 V3.0 in Ender 3 Pro with CR-Touch
2. Install [firmware-ender3-bltouch-for-z-homing.bin](https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/blob/master/firmware/V3.0/Marlin/firmware-ender3-bltouch-for-z-homing.bin)
3. Auto-Home

**Expected behavior**
Z-Homing success.

**Actual behavior**
When the X & Y Homing complete, the print head goes to the middle of the bed, about 10-20 mm off the bed, then the CR-Touch repeatedly deploys and retracts the pin, the Z-axis does not move otherwise.

### Additional Information
If I install the 3.0 Marlin firmware without the Z-homing, it will use the CR-Touch to ABL and the z-stop, but not the CR-Touch probe for z-Homing.

**Comment by Taomyn** [comment]
I was having a similar issue with my v3 but using a custom firmware I'm currently porting from my old v1.2 board, though for me it didn't actually deploy the probe, it would just sit there.

You might fix it by either connecting the black and white cables into the 2-pin Z-endstop port, or if you have your own code enable the following:

// Force the use of the probe for Z-axis homing
#define USE_PROBE_FOR_Z_HOMING

I never needed this on the v1.2 as it was splitting the BL-Touch cables in this way as the probe port was only 3 pins, but now with the v3 it seems to be working now and so the full 5-pin probe socket can be used and not split the cables.

**Comment by Wonkothsane** [comment]
> if you have your own code enable the following: 
> // Force the use of the probe for Z-axis homing #define USE_PROBE_FOR_Z_HOMING
>
Will give it a shot, thanks.

**Comment by Wonkothsane** [comment]
>if you have your own code enable the following:
>// Force the use of the probe for Z-axis homing #define USE_PROBE_FOR_Z_HOMING
>
>Will give it a shot, thanks.


This issue persists.

**Comment by Taomyn** [comment]
@Wonkothsane you're welcome to check out my fork to see if anything of it helps, I customises the README.md with extra info on my hardware and code changes I made

https://github.com/Taomyn/Marlin

**Comment by Wonkothsane** [comment]
@Taomyn I appreciate your assistance. Thank you.  I took a look at your Marlin branch. It appears similar to the config I bult locally here.   I got frustrated with it yesterday and built a Klipper firmware and flashed that. I got everything working on the Klipper firmware.  CR Touch works fine and the first layer is buttery smooth.

The only change I made to get the CR Touch working was to add a pull-up to the pin it uses for sensor signal (i.e.: sensor_pin: **^**PC14).  

Perhaps I missed a similar setting in the Marlin Firmware?  If I ever switch back, I will look for a place to check this.

**Comment by MavrEars** [comment]
Here is Ender 3 Pro compiled firmware for SKR mini E3 V3 + CR TOUCH/BL TOUCH bugfix 2.0.x https://disk.yandex.ru/d/EaPAVP5BTo2g5w

Thanks this FAQ: https://www.makenprint.uk/3d-printing/3d-firmware-guides/marlin/consolidated-marlin-guide/

**Comment by karmavibes7** [comment]
hi all, i search many informations for the ender 5 cr touch firmware with an skr e3 v3. but i find nothing. 
i don't know what to do, some infos i've read make me think that i have a particular setup and don't find anything working for me.
Can someone help me to understand the problem and find an issue?
thanks

**Comment by jakedoesgithub** [comment]
Hi it’s not you it’s the recompiled firmware it’s incorrect here are the older btt version that work https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/tree/d5fc619c2a4aadc889c47680af351310f521e850/firmware/V2.0

**Comment by TheShield167** [comment]
Is there a working one for V3.0 yet?

**Comment by yellowcooln** [comment]
> **UPDATE — DO NOT USE THIS FIRMWARE:** I withdrew the release after `G29` caused an unsafe printer halt during further hardware testing. I am investigating the probe geometry and failure before republishing anything.

I ran into the same behavior with the old BTT precompiled firmware: X/Y would home, the carriage moved to the center, the CR Touch repeatedly deployed/retracted, and Z never descended.

I built a replacement from official Marlin 2.1.2.8 and released it on my SKR Mini E3 fork:

https://github.com/yellowcooln/BIGTREETECH-SKR-mini-E3/releases/tag/ender3-skr-mini-e3-v3-crtouch-marlin-2.1.2.8

This has now been flashed and hardware-tested successfully on my original Ender 3 with:

- SKR Mini E3 V3.0
- Stock Ender 3 12864 rotary display
- Genuine CR Touch connected as one five-wire plug to the dedicated probe header
- Mechanical Z-stop disconnected
- CR Touch used for both Z homing and 5x5 bilinear leveling
- OctoPrint over USB at 115200 baud

The build uses PA1 for probe control and the dedicated PC14 input for the trigger; PC2 / the physical Z-stop connector is unused. The release includes `firmware.bin`, checksums, final configurations, the build log, and cautious commissioning notes.

Please only use it if your hardware and wiring match the documented configuration exactly. The X/Y probe offset is provisional and the Z offset must be calibrated on the printer. I released this only to help people having the same problem; it comes with no support and should be used at your own risk.

**Comment by kenpoh01** [comment]
I fixed that problem with a 3D Touch by using the bug fix release of marlin.
