### ISSUE TITLE
TFT 35 v2 won't connect

### ISSUE THREAD

**Issue by Hobhub** [bigtreetech/BIGTREETECH-SKR-mini-E3#60]
currently, I am getting _no printer attached_ messages 
I am plugged into the TFT slot on the mainboard and the rs232 slot on the screen.

**Comment by Modredo** [comment]
same here, the text disappears after a few moments but nothing I press on the screen does anything. Its like its stuck on the main menu. Connecting to Pronterface shows the board is alive and controllable via USB connection.

**Comment by Hobhub** [comment]
I have been in contact with BigTreeTech and after posting a video with my problems they suggested to check for shorts from RX to ground, and TX to ground.

**Comment by Aquaman7** [comment]
i have the SKR mini E3 board, where do i connect it and what direction? the diagram dose not show where and how...

**Comment by Hobhub** [comment]
this is the pin diagram for the mini E3 v1.2
https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/blob/master/hardware/BTT%20SKR%20MINI%20E3%20V1.2/BTT%20SKR%20MINI%20E3%20V1.2PIN.pdf

there is a port labelled TFT this is what you should plug into. On the cable, the single connector should be the 5v use that to orient it.
![wiring](https://user-images.githubusercontent.com/56853488/68256273-7c5f4680-0094-11ea-94aa-ca037c216403.png)

**Comment by Aquaman7** [comment]
omg thank you, i got t up and running, just need to figure out how to add my bl touch

**Comment by Hobhub** [comment]
so is your tft35 connecting to the printer?

**Comment by Aquaman7** [comment]
> so is your tft35 connecting to the printer?

yes it is now, trying to figure out how to add the BL touch now... if you have any ideas on that would be helpful

**Comment by Hobhub** [comment]
I have had troubles too because on version 1.2 of the board they changed the pin layout for the BlTouch watch this video it explains this.
https://www.youtube.com/watch?v=ikHhzOIlHPg

**Comment by Hobhub** [comment]
this is my compiled version of marlin with bltouch enabled (you will need to change z_probe offsets because I am using a hero me fan duct)
https://drive.google.com/file/d/15o6qMwFXJAuUR8rzoibim3WETKbNvUNn/view?usp=sharing

**Comment by Aquaman7** [comment]
> this is my compiled version of marlin with bltouch enabled (you will need to change z_probe offsets because I am using a hero me fan duct)
> https://drive.google.com/file/d/15o6qMwFXJAuUR8rzoibim3WETKbNvUNn/view?usp=sharing
> 
> probe offset info: http://marlinfw.org/docs/gcode/M851.html

i also have the Hero me fan duct... how to i use the bin file? i apologize but I'm new to programing and still learning but this will work perfect for me, should i just cut and paste to an sd card and insert and turn it on?

**Comment by Hobhub** [comment]
yes just put it on the sd card and plug it into the printer then boot up. You might have to adjust the z_probe Z offset to get your level right but what I've set should work.

Also on my TFT35 BigTreeTech reckons it's a defect and are sending me a new one for free, so props to them.

**Comment by Aquaman7** [comment]
> yes just put it on the micro sd card and plug it into the printer mainboard then boot up. You might have to adjust the z_probe Z offset to get your level right but what I've set should work.
> 
> Also on my TFT35 BigTreeTech reckons it's a defect and are sending me a new one for free, so props to them.

thats awesome, they are a good company
