### ISSUE TITLE
skr mini E3 v2.0 extruder clicking

### ISSUE THREAD

**Issue by govorun17** [bigtreetech/BIGTREETECH-SKR-mini-E3#621]
### Description

after board installing on my Ender 3 pro stock extruder started to click, i tried all solutions from web. I assume that the driver is overheating or it does not have enough amperage

I aploaded firmware from git.

**Comment by noskilljustluck** [comment]
got it to work? have the same issue. the extruder is unloaded but the motor is jumping back and forth

**Comment by govorun17** [comment]
ok, i've solved problem by myself.
firstly i removed thermal tape and used thermally conductive adhesive up to 300 Celsius
secondly i found setting of amperage (Look at picture)
marlin 2.0.7.2 
on stock steppers not recomended to set apper than 1000 mA.
![MyCollages](https://user-images.githubusercontent.com/55958773/155891239-bce0efc9-f440-4262-a57b-e8ddbb7721e9.png)
