### ISSUE TITLE
Свист вентиляторов

### ISSUE THREAD

**Issue by Pacha5** [bigtreetech/BIGTREETECH-SKR-mini-E3#655]
Плата SKR MINI E3 V3.
Всё работает. Но при попытке уменьшить скорость вентиляторов, они начинают пищать (свистеть). Пробовал разные вентиляторы, ничего не меняется.
На старой плате эти же вентиляторы работали тихо. Скорость можно было ставить и 5% и они работали тихо. На этой плате при этих параметрах только свист и никакого движения лопастей.

**Comment by radek8** [comment]
You used the wrong website and language.
This is not Ebay.
Please close the ticket
