### ISSUE TITLE
UART not working with raspberry pi 3 B+

### ISSUE THREAD

**Issue by EduMota** [bigtreetech/BIGTREETECH-SKR-mini-E3#682]
I'm trying to identify the pins PA3 and PA2 on the skr mini e3 v3, but they are not listed at board pinout pdf.

I want to check the connections to make sure that everything is ok, because I follow the setup recommended [here](https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/tree/master/firmware/V3.0/Klipper), but without result, my board not respond to klipper, and continue getting the error 
`mcu 'mcu': Unable to connect
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Error configuring printer`

**Comment by radek8** [comment]
PA2 and PA3 
There are RX and TX pins on the TFT connector.

**Comment by EduMota** [comment]
Then I think some thing is off.

My printer.cfg 
![Screenshot from 2022-09-11 18-51-24](https://user-images.githubusercontent.com/32824189/189550529-928f981a-9c77-42eb-9a4c-4f7bcbdeddec.png)

My /boot/config.txt
![Screenshot from 2022-09-11 18-52-03](https://user-images.githubusercontent.com/32824189/189550579-9d8f2b99-2aa0-470c-8b61-5a66ecc0e265.png)

My /boot/cmdline.txt
![Screenshot from 2022-09-11 18-51-24](https://user-images.githubusercontent.com/32824189/189550649-642e0009-00c7-4ff4-893b-6ef2c3a0ebcc.png)

My connections on skr mini.
![20220911_183457](https://user-images.githubusercontent.com/32824189/189550882-1d718de5-0d02-487e-8e37-2ec9c5acfa42.jpg)

My connections on raspberry pi 3 b+
![20220911_183521](https://user-images.githubusercontent.com/32824189/189550911-b5d2a281-f631-4da7-acfe-396bae709e3b.jpg)

Pinout of raspberry:
![raspberry-pi-15b](https://user-images.githubusercontent.com/32824189/189551051-8c68951c-760b-4b03-8fe8-5e01ab983e4d.jpg)

**Comment by radek8** [comment]
I won't help you. 
I don't use Raspberry or Klipper.

**Comment by EduMota** [comment]
Ok, now it's working, for someone with the same issue, that is how I figured out.

I plugged an usb/ttl adapter on raspberry and my notebook, on Linux host executed:
~~~
minicom -b <baud rate> -D <serial>
~~~

I could find out that my raspberry was with a high baud rate 300000, so I just recompile Klipper and flash it on printer board, and in `printer.cfg` added the 
~~~
[mcu]
baud:300000
~~~
