### ISSUE TITLE
Ender 3 freezes with buzzer when printing from SD

### ISSUE THREAD

**Issue by ManiRX100** [bigtreetech/BIGTREETECH-SKR-mini-E3#72]
Hi all
My SKR mini E3 V1.2 board was working fine with the latest firmware. Suddenly , the ender 3 started to freeze when I start to print from SD card. Previously I didnt have this issue. Every time I reinsert the SD card and print from SD, the same happens. Any ideas? 
I checked other threads, some did not have this issue and for some the issue reappears.

**Comment by maddingamer** [comment]
Do you have the USB cable connected with Cura opened?

**Comment by ManiRX100** [comment]
@maddingamer No. I used only SD card.

**Comment by MyDog-andme** [comment]
About my Ender 3 freezes with buzzer when setting the board temp. (Press to set Buzzer starts and that's it. pull the plug.

**Comment by AkiraKJ** [comment]
What was the resolution?
