### ISSUE TITLE
[BUG] No Printer Attached - SKR Mini E3 V2 and TFT35-E3 V3.0.1

### ISSUE THREAD

**Issue by JLiraEJ8** [bigtreetech/BIGTREETECH-SKR-mini-E3#751]
Hello everyone, I'm still a newbie in this domain and I would appreciate it if you could confirm my doubt.
I have an Aquila X2 and I installed a SKR Mini E3 V2 and a TFT35-E3 V3.0.1 with BLTouch and i updated the firmware.
Everything worked perfectly until I changed the support of the TFT that I had printed and after that the message "No Printer Attached" appeared and the screen on the right side started to heat up a lot and a stain appeared. I bought another TFT and the same thing happens.
Could it be that when I installed the TFT in the support when tightening the screws it crushed some wire? I've tested with others and the same thing happens.
I think it was the motherboard that failed but it's work whell in Marlin mode (with the TFT cable disconnected because it heats up the screen a lot)
Does anyone know the voltage of the different TFT pins on the motherboard Or what could have happened apart from what I described?
Thank you for your help.

![20230817_121826](https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/assets/142908691/ae8a887e-d838-4f95-88eb-df2964dd1643)
![20230817_121841](https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/assets/142908691/91fc98da-417e-48bc-9427-d36072e7c943)
![20230817_121908](https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/assets/142908691/5af07311-d496-49b9-b46e-617de774cbed)
![20230817_122029](https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/assets/142908691/a12057bd-441d-4f22-9ab0-56a580c083a6)

**Comment by JLiraEJ8** [comment]
Problem Solved

**Comment by akkoaskr** [comment]
How was the problem solved?

**Comment by JLiraEJ8** [comment]
Hello, sorry for the delay. 
As you can see in one of the photos, on the TFT35 the LCD cable is not connected in the right plug (connected in the SWD) the right plug is RS232... my fault.
